print("Hello and welcome to this challenge\n I ask you every questions for to night menu")
name:str=input("Your name please: ")
food:str=input("Giv me a food name do you prefer: ")
plant:str=input("type of plant for food: ")
cooking:str=input("Method of cooking: ")
burned:str=input("A word to describ burned food: ")
householdItem:str=input("A household item: ")
print("\n Thank you ",name," for your answers")
print("Your menu")
print(cooking ,food," to",plant, "with", burned, "on a bed of",householdItem)
